[project]
name = "bikespace-data"
version = "0.1.0"
description = "New BikeSpace Toronto Bicycle Parking Map Data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "geojson>=3.2.0",
    "geopandas>=1.1.1",
    "numpy>=2.2.4",
    "overpass>=0.7.2",
    "pandas>=2.2.3",
    "pandera[geopandas]>=0.24.0",
    "pathlib>=1.0.1",
    "progress>=1.6.1",
    "pyarrow>=20.0.0",
    "pytest-cov>=6.2.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "shapely>=2.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-mock>=3.14.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "-s --cov=src --cov-report=term-missing"

[tool.coverage.run]
omit = [
    # omit anything in a test directory anywhere
    "*/tests/*",
    ]

[tool.coverage.report]
exclude_also = [
    'if __name__ == .__main__.:',
    '@(abc\.)?abstractmethod',
]
