# This workflow will install Python dependencies and run the data pipeline script

name: Run Update

on: # workflow_dispatch
  schedule:
    - cron: '00 9 * * 1' # only on Mondays 9:00am UTC (4:00am ST or 5:00am DT in Toronto)

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run data pipeline script
      run: python "Data Pipeline/data_pipeline.py"
    - name: Update repository
      run: |
        git config user.email ${{ secrets.BOT_EMAIL }}
        git config user.name "tallcoleman-bot"
        git add --all
        git commit -m "BOT - ran data pipeline update"
        git fetch origin main
        git push origin main
